import type { Event } from "@/lib/types"

export const dummyEvents: Event[] = [
  {
    event_id: "evt_001",
    organizer: "StarkZap",
    name: "Starkzap blitz After Hours",
    location: "Berlin, Germany",
    start_time: "2026-06-15T21:00:00",
    age_requirement: 18,
    max_attendees: 500,
    ticket_count: 312,
    active: true,
  },
  {
    event_id: "evt_002",
    organizer: "StarkPass DAO",
    name: "ZK Proofs Workshop",
    location: "Online",
    start_time: "2026-04-20T14:00:00",
    age_requirement: 16,
    max_attendees: 200,
    ticket_count: 198,
    active: true,
  },
  {
    event_id: "evt_003",
    organizer: "0xabcd...5678",
    name: "Privacy Night NYC",
    location: "Brooklyn, NY",
    start_time: "2026-05-10T19:00:00",
    age_requirement: 21,
    max_attendees: 120,
    ticket_count: 87,
    active: true,
  },
  {
    event_id: "evt_004",
    organizer: "Cairo Labs",
    name: "Cairo 3.0 Launch",
    location: "Lisbon, Portugal",
    start_time: "2026-07-01T10:00:00",
    age_requirement: 0,
    max_attendees: 300,
    ticket_count: 0,
    active: false,
  },
  {
    event_id: "evt_005",
    organizer: "0x9999...ffff",
    name: "Starknet Hackathon",
    location: "San Francisco, CA",
    start_time: "2026-08-12T08:00:00",
    age_requirement: 18,
    max_attendees: 150,
    ticket_count: 150,
    active: true,
  },
  {
    event_id: "evt_006",
    organizer: "DevCon Team",
    name: "Account Abstraction Day",
    location: "Singapore",
    start_time: "2026-09-05T09:30:00",
    age_requirement: 0,
    max_attendees: 400,
    ticket_count: 221,
    active: true,
  },
  {
    event_id: "evt_007",
    organizer: "0xdead...beef",
    name: "Private Identity Meetup",
    location: "London, UK",
    start_time: "2026-03-28T18:00:00",
    age_requirement: 18,
    max_attendees: 80,
    ticket_count: 45,
    active: true,
  },
  {
    event_id: "evt_008",
    organizer: "StarkZap",
    name: "Gasless UX Conference",
    location: "Dubai",
    start_time: "2026-10-15T10:00:00",
    age_requirement: 0,
    max_attendees: 250,
    ticket_count: 12,
    active: true,
  },
  {
    event_id: "evt_009",
    organizer: "0x1111...2222",
    name: "Validator Node Bootcamp",
    location: "Remote",
    start_time: "2026-04-01T12:00:00",
    age_requirement: 0,
    max_attendees: 100,
    ticket_count: 100,
    active: false,
  },
  {
    event_id: "evt_010",
    organizer: "Ecosystem Grants",
    name: "Starknet Builders Dinner",
    location: "Paris, France",
    start_time: "2026-06-22T19:00:00",
    age_requirement: 18,
    max_attendees: 60,
    ticket_count: 33,
    active: true,
  },
]

export function getEventById(eventId: string): Event | undefined {
  return dummyEvents.find((e) => e.event_id === eventId)
}
